DROP TABLE IF EXISTS user_article;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS sections;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS status;